language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.8
  
install: pip install tox-travis codecov

script: tox

after_success:
  - codecov

matrix:
  allow_failures:
    - python: 2.7
